In [1]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder

In [45]:
df = pd.read_csv('C:/Users/Prem/loan-approval-ml-project/data/loan_data.csv')

df.head()

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,LP001003,Male,Yes,1,Graduate,No,4583,1508.0,128.0,360.0,1.0,Rural,N
1,LP001005,Male,Yes,0,Graduate,Yes,3000,0.0,66.0,360.0,1.0,Urban,Y
2,LP001006,Male,Yes,0,Not Graduate,No,2583,2358.0,120.0,360.0,1.0,Urban,Y
3,LP001008,Male,No,0,Graduate,No,6000,0.0,141.0,360.0,1.0,Urban,Y
4,LP001013,Male,Yes,0,Not Graduate,No,2333,1516.0,95.0,360.0,1.0,Urban,Y

In [46]:
df.drop('Loan_ID', axis=1, inplace=True)
df.head()

,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,Male,Yes,1,Graduate,No,4583,1508.0,128.0,360.0,1.0,Rural,N
1,Male,Yes,0,Graduate,Yes,3000,0.0,66.0,360.0,1.0,Urban,Y
2,Male,Yes,0,Not Graduate,No,2583,2358.0,120.0,360.0,1.0,Urban,Y
3,Male,No,0,Graduate,No,6000,0.0,141.0,360.0,1.0,Urban,Y
4,Male,Yes,0,Not Graduate,No,2333,1516.0,95.0,360.0,1.0,Urban,Y

In [47]:
df.isnull().sum()

Gender                5
Married               0
Dependents            8
Education             0
Self_Employed        21
ApplicantIncome       0
CoapplicantIncome     0
LoanAmount            0
Loan_Amount_Term     11
Credit_History       30
Property_Area         0
Loan_Status           0
dtype: int64

### Handling Missing values

In [48]:
df['Gender'] = df['Gender'].fillna(df['Gender'].mode()[0])
df['Dependents']=df['Dependents'].fillna(df['Dependents'].mode()[0])
df['Self_Employed']=df['Self_Employed'].fillna(df['Self_Employed'].mode()[0])

df['Loan_Amount_Term']=df['Loan_Amount_Term'].fillna(df['Loan_Amount_Term'].median())
df['Credit_History']=df['Credit_History'].fillna(df['Credit_History'].median())

In [49]:
df.isnull().sum()

Gender               0
Married              0
Dependents           0
Education            0
Self_Employed        0
ApplicantIncome      0
CoapplicantIncome    0
LoanAmount           0
Loan_Amount_Term     0
Credit_History       0
Property_Area        0
Loan_Status          0
dtype: int64

### Separating Input feature and target feature

In [50]:
X = df.drop('Loan_Status', axis=1)
y = df['Loan_Status']

In [51]:
X.select_dtypes(include='object').columns

Index(['Gender', 'Married', 'Dependents', 'Education', 'Self_Employed',
       'Property_Area'],
      dtype='object')

### Encoding

In [52]:
le = LabelEncoder()

for col in X.select_dtypes(include='object').columns:
    X[col]=le.fit_transform(X[col])

In [53]:
y = y.map({'N':0, 'Y':1})

In [54]:
X.head()

,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area
0,1,1,1,0,0,4583,1508.0,128.0,360.0,1.0,0
1,1,1,0,0,1,3000,0.0,66.0,360.0,1.0,2
2,1,1,0,1,0,2583,2358.0,120.0,360.0,1.0,2
3,1,0,0,0,0,6000,0.0,141.0,360.0,1.0,2
4,1,1,0,1,0,2333,1516.0,95.0,360.0,1.0,2

In [55]:
y.head()

0    0
1    1
2    1
3    1
4    1
Name: Loan_Status, dtype: int64

### train_test_split

In [56]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [57]:
print(X_train.shape)

(304, 11)

In [58]:
print(X_test.shape)

(77, 11)

In [59]:
print(y_train.shape)

(304,)

In [60]:
print(y_test.shape)

(77,)

### Model Training

In [61]:
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier

from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
from sklearn.preprocessing import StandardScaler

#### Scaling X for logistic Regression

In [62]:
scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.fit_transform(X_test)

#### Logistic Regression Model

In [63]:
lr = LogisticRegression(max_iter=1000)
lr.fit(X_train_scaled, y_train)

y_pred_lr = lr.predict(X_test_scaled)

print('Logistic Regression Accuracy: ', accuracy_score(y_test, y_pred_lr))
print('\nConfusion Matrix:\n', confusion_matrix(y_test, y_pred_lr))
print('\nClassification Report:\n', classification_report(y_test, y_pred_lr))

Logistic Regression Accuracy:  0.8181818181818182

Confusion Matrix:
 [[ 7 14]
 [ 0 56]]

Classification Report:
               precision    recall  f1-score   support

           0       1.00      0.33      0.50        21
           1       0.80      1.00      0.89        56

    accuracy                           0.82        77
   macro avg       0.90      0.67      0.69        77
weighted avg       0.85      0.82      0.78        77

#### Decision Tree model

In [66]:
dt = DecisionTreeClassifier(random_state=42)
dt.fit(X_train, y_train)

y_pred_dt = dt.predict(X_test)

print('Decision Tree Accuracy: ', accuracy_score(y_test, y_pred_dt))
print('\nConfusion Matrix:\n', confusion_matrix(y_test, y_pred_dt))
print('\nClassification Report:\n', classification_report(y_test, y_pred_dt))

Decision Tree Accuracy:  0.7272727272727273

Confusion Matrix:
 [[ 8 13]
 [ 8 48]]

Classification Report:
               precision    recall  f1-score   support

           0       0.50      0.38      0.43        21
           1       0.79      0.86      0.82        56

    accuracy                           0.73        77
   macro avg       0.64      0.62      0.63        77
weighted avg       0.71      0.73      0.71        77

#### Random Forest Model

In [67]:
rf = RandomForestClassifier(random_state=42)
rf.fit(X_train, y_train)

y_pred_rf = rf.predict(X_test)

print('Random Forest Accuracy: ', accuracy_score(y_test, y_pred_rf))
print('\nConfusion Matrix:\n', confusion_matrix(y_test, y_pred_rf))
print('\nClassification Report:\n', classification_report(y_test, y_pred_rf))

Random Forest Accuracy:  0.8051948051948052

Confusion Matrix:
 [[ 7 14]
 [ 1 55]]

Classification Report:
               precision    recall  f1-score   support

           0       0.88      0.33      0.48        21
           1       0.80      0.98      0.88        56

    accuracy                           0.81        77
   macro avg       0.84      0.66      0.68        77
weighted avg       0.82      0.81      0.77        77

In [68]:
print("Logistic Regression:", accuracy_score(y_test, y_pred_lr))
print("Decision Tree:", accuracy_score(y_test, y_pred_dt))
print("Random Forest:", accuracy_score(y_test, y_pred_rf))

Logistic Regression: 0.8181818181818182
Decision Tree: 0.7272727272727273
Random Forest: 0.8051948051948052

#### Balanced Logistic Regression

In [69]:
lr_balanced = LogisticRegression(class_weight='balanced', max_iter=1000)
lr_balanced.fit(X_train_scaled, y_train)

y_pred_lr_bal = lr_balanced.predict(X_test_scaled)

print('Balanced Logistic Regression Accuracy: ', accuracy_score(y_test, y_pred_lr_bal))
print('\nConfusion Matrix:\n', confusion_matrix(y_test, y_pred_lr_bal))
print('\nClassification Report:\n', classification_report(y_test, y_pred_lr_bal))

Balanced Logistic Regression Accuracy:  0.7532467532467533

Confusion Matrix:
 [[ 9 12]
 [ 7 49]]

Classification Report:
               precision    recall  f1-score   support

           0       0.56      0.43      0.49        21
           1       0.80      0.88      0.84        56

    accuracy                           0.75        77
   macro avg       0.68      0.65      0.66        77
weighted avg       0.74      0.75      0.74        77

In [70]:
import joblib
import os

In [72]:
os.makedirs('C:/Users/Prem/loan-approval-ml-project/artifacts', exist_ok=True)

In [73]:
joblib.dump(lr, 'C:/Users/Prem/loan-approval-ml-project/artifacts/loan_model.pkl')
joblib.dump(scaler, 'C:/Users/Prem/loan-approval-ml-project/artifacts/scaler.pkl')

['C:/Users/Prem/loan-approval-ml-project/artifacts/scaler.pkl']

In [74]:
os.listdir('C:/Users/Prem/loan-approval-ml-project/artifacts')

['loan_model.pkl', 'scaler.pkl']